#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

ANDROID_BOOTARGS = "earlycon=uart8250,mmio32,0xff1a0000 coherent_pool=1m"
GENERATED_LINUX_DTSI = "rk3399-rock960-android-base.dtsi"
UPSTREAM_WIFI_SELECTOR = 'wifi_chip_type = "ap6354"'
ROCK960_WIFI_SELECTOR = 'wifi_chip_type = "ap6356s"'

ANDROID_GLUE = r'''

/*
 * ROCK960 Android 11 glue generated by ROCK960-AndroidTV11-ASUS-BSP.
 *
 * Board wiring/regulators/SDIO/UART/USB/PCIe/eMMC definitions come from the
 * ROCK960 A/B DTS already present in the exact ASUS 2.0.8 kernel tag. The
 * generated Android DTS corrects its historical AP6354 module label to AP6356S
 * while keeping the SDIO/GPIO/clock wiring unchanged.
 * The source board DTS inherits rk3399-linux.dtsi, so the generator swaps that
 * include for a sanitized sibling copy (Linux root= bootargs removed) and then
 * adds only the Android display/firmware state needed for this port.
 */
/ {
	firmware {
		firmware_android: android {};
	};
};

&vopb {
	support-multi-area;
	status = "okay";
};

&vopb_mmu {
	status = "okay";
};

&vopl {
	support-multi-area;
	status = "okay";
};

&vopl_mmu {
	status = "okay";
};

&hdmi {
	ddc-i2c-scl-high-time-ns = <9625>;
	ddc-i2c-scl-low-time-ns = <10000>;
	status = "okay";
};

&display_subsystem {
	status = "okay";
	ports = <&vopb_out>, <&vopl_out>;
};

&route_hdmi {
	status = "okay";
	connect = <&vopb_out_hdmi>;
};

&i2s2 {
	rockchip,bclk-fs = <128>;
	status = "okay";
};

&rng {
	status = "okay";
};
'''


def sanitize_linux_dtsi(linux_dtsi: Path, generated_dtsi: Path) -> None:
    text = linux_dtsi.read_text()
    if "root=PARTUUID=" not in text or "rootfstype=ext4" not in text:
        raise SystemExit(
            "rk3399-linux.dtsi no longer has the expected Linux root bootargs; "
            "refusing a blind rewrite"
        )

    pattern = re.compile(r'(?m)^(\s*)bootargs\s*=\s*"[^"]*root=PARTUUID=[^"]*";\s*$')
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise SystemExit(
            f"expected exactly one Linux root bootargs line in {linux_dtsi}; found {len(matches)}"
        )
    indent = matches[0].group(1)
    text = pattern.sub(f'{indent}bootargs = "{ANDROID_BOOTARGS}";', text, count=1)
    if "root=PARTUUID=" in text or "rootfstype=ext4" in text:
        raise SystemExit("Linux root bootargs survived sanitization")
    generated_dtsi.write_text(text)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    base = Path(args.base).resolve()
    out = Path(args.output).resolve()
    linux_dtsi = base.parent / "rk3399-linux.dtsi"
    generated_dtsi = base.parent / GENERATED_LINUX_DTSI

    if not linux_dtsi.is_file():
        raise SystemExit(f"missing expected Linux base include: {linux_dtsi}")

    text = base.read_text()
    required = [
        'model = "ROCK960',
        'compatible = "rockchip,rock960"',
        UPSTREAM_WIFI_SELECTOR,
        '&sdhci', '&sdio0', '&uart0', '&hdmi', '&usbdrd_dwc3_0', '&gpu',
        'fusb30x@22', '&pcie0', 'rockchip,remotectl-pwm',
    ]
    missing = [x for x in required if x not in text]
    if missing:
        raise SystemExit(
            "base DTS does not look like the expected ROCK960 A/B tree; missing: "
            + ", ".join(missing)
        )

    include_line = '#include "rk3399-linux.dtsi"'
    if text.count(include_line) != 1:
        raise SystemExit("expected ROCK960 base DTS to include rk3399-linux.dtsi exactly once")

    if text.count(UPSTREAM_WIFI_SELECTOR) != 1:
        raise SystemExit(
            "expected exactly one historical AP6354 wifi_chip_type selector in the pinned "
            "ROCK960 DTS; refusing a blind Wi-Fi rewrite"
        )

    sanitize_linux_dtsi(linux_dtsi, generated_dtsi)
    text = text.replace(include_line, f'#include "{GENERATED_LINUX_DTSI}"', 1)
    text = text.replace(UPSTREAM_WIFI_SELECTOR, ROCK960_WIFI_SELECTOR, 1)
    if UPSTREAM_WIFI_SELECTOR in text or ROCK960_WIFI_SELECTOR not in text:
        raise SystemExit("failed to generate the AP6356S ROCK960 Wi-Fi selector")

    # ASUS/Tinker 2.0.8 ROCK960 DTS contains a stale &vpu block.
    # This kernel exposes vdpu/vepu/vpu_mmu instead, so leaving &vpu
    # causes dtc to fail with "Label or path vpu not found".
    stale_vpu = '''&vpu {
\tstatus = "okay";
\t/* 0 means ion, 1 means drm */
\t//allocator = <0>;
};
'''
    if text.count(stale_vpu) != 1:
        raise SystemExit(
            "expected exactly one stale ASUS/Tinker &vpu block; "
            f"found {text.count(stale_vpu)}"
        )
    text = text.replace(stale_vpu, "", 1)

    out.write_text(text.rstrip() + ANDROID_GLUE + "\n")

    print(generated_dtsi)
    print(out)


if __name__ == "__main__":
    main()
