#!/usr/bin/env python3
import argparse
import re
import shutil
from pathlib import Path

TEXT_SUFFIXES = {".mk", ".xml", ".conf", ".cfg", ".txt", ".in", ".rc", ".kl", ".idc", ".prop", ".bp", ".sh", ""}


def replace_text_tree(root: Path, old: str, new: str) -> None:
    for p in root.rglob("*"):
        if not p.is_file() or p.suffix not in TEXT_SUFFIXES:
            continue
        try:
            text = p.read_text()
        except UnicodeDecodeError:
            continue
        if old in text:
            p.write_text(text.replace(old, new))


def set_make_var(text: str, name: str, value: str) -> str:
    pat = re.compile(rf"^(\s*{re.escape(name)}\s*:?=).*$", re.M)
    replacement = rf"\1 {value}"
    if pat.search(text):
        return pat.sub(replacement, text)
    return text.rstrip() + f"\n{name} := {value}\n"


def set_make_var_before(text: str, name: str, value: str, marker: str) -> str:
    """Set a make variable before an inherited makefile evaluates it."""
    pat = re.compile(rf"^\s*{re.escape(name)}\s*:?=.*$\n?", re.M)
    text = pat.sub("", text)
    idx = text.find(marker)
    if idx < 0:
        raise SystemExit(f"cannot place {name}: inherit marker not found: {marker}")
    return text[:idx] + f"{name} := {value}\n" + text[idx:]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True)
    ap.add_argument("--product", default="rock960_atv")
    ap.add_argument("--model", default="ROCK960 Android TV")
    ap.add_argument("--avb", choices=["0", "1"], default="0")
    ap.add_argument("--widevine", choices=["0", "1"], default="1")
    ap.add_argument("--playready", choices=["0", "1"], default="0")
    ap.add_argument("--gms", choices=["0", "1"], default="0")
    ap.add_argument("--gtvs", choices=["0", "1"], default="0")
    ap.add_argument("--camera", choices=["0", "1"], default="0")
    ap.add_argument("--ethernet", choices=["0", "1"], default="0")
    args = ap.parse_args()

    source = Path(args.source).resolve()
    src = source / "device/rockchip/rk3399/rk3399_atv"
    dst = source / f"device/rockchip/rk3399/{args.product}"
    if not src.is_dir():
        raise SystemExit(f"missing upstream product: {src}")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, symlinks=True)

    old_mk = dst / "rk3399_atv.mk"
    new_mk = dst / f"{args.product}.mk"
    if not old_mk.exists():
        raise SystemExit(f"upstream product makefile missing: {old_mk}")
    old_mk.rename(new_mk)

    replace_text_tree(dst, "device/rockchip/rk3399/rk3399_atv", f"device/rockchip/rk3399/{args.product}")
    replace_text_tree(dst, "rk3399_atv", args.product)

    board = dst / "BoardConfig.mk"
    text = board.read_text()
    settings = {
        "PRODUCT_KERNEL_DTS": "rk3399-rock960-ab-android",
        # Keep android-10.config here: device/rockchip/common/BoardConfig.mk appends android-11.config.
        "PRODUCT_KERNEL_CONFIG": "rockchip_defconfig android-10.config",
        "PRODUCT_USE_PREBUILT_GTVS": "yes" if args.gtvs == "1" else "no",
        "BUILD_WITH_GOOGLE_FRP": "false",
        "BUILD_WITH_GOOGLE_GMS_EXPRESS": "true" if args.gms == "1" else "false",
        "BUILD_WITH_MICROSOFT_PLAYREADY": "true" if args.playready == "1" else "false",
        "BOARD_AVB_ENABLE": "true" if args.avb == "1" else "false",
        "BOARD_WIDEVINE_OEMCRYPTO_LEVEL": "3" if args.widevine == "1" else "0",
    }
    for key, value in settings.items():
        text = set_make_var(text, key, value)
    text += "\n# ROCK960 board-level bring-up overrides (generated by controller)\n"
    text += f"BOARD_CAMERA_SUPPORT := {'true' if args.camera == '1' else 'false'}\n"
    text += f"BOARD_CAMERA_SUPPORT_EXT := {'true' if args.camera == '1' else 'false'}\n"
    text += f"BOARD_HS_ETHERNET := {'true' if args.ethernet == '1' else 'false'}\n"
    # The RK3399 generic BoardConfig advertises tablet-style gravity/light sensors and
    # enables factory PCBA tests. ROCK960 A/B has no such onboard Android sensor set;
    # leave expansion-header sensors to a later explicit board overlay instead of
    # advertising hardware that is not physically present.
    text += "BOARD_GRAVITY_SENSOR_SUPPORT := false\n"
    text += "BOARD_LIGHT_SENSOR_SUPPORT := false\n"
    text += "BOARD_COMPASS_SENSOR_SUPPORT := false\n"
    text += "BOARD_GYROSCOPE_SENSOR_SUPPORT := false\n"
    text += "BOARD_PROXIMITY_SENSOR_SUPPORT := false\n"
    text += "BOARD_PRESSURE_SENSOR_SUPPORT := false\n"
    text += "BOARD_TEMPERATURE_SENSOR_SUPPORT := false\n"
    text += "BOARD_HAVE_FLASH := false\n"
    text += "TARGET_ROCKCHIP_PCBATEST := false\n"
    text += "BOARD_HAS_STRESSTEST_APP := false\n"
    text += "BUILD_WITHOUT_BATTERY := true\n"
    text += "BOARD_SENSOR_MPU_PAD := false\n"
    board.write_text(text)

    product = new_mk
    text = product.read_text()
    text = set_make_var(text, "PRODUCT_NAME", args.product)
    text = set_make_var(text, "PRODUCT_DEVICE", args.product)
    text = set_make_var(text, "PRODUCT_BRAND", "rockchip")
    text = set_make_var(text, "PRODUCT_MODEL", args.model)
    text = set_make_var(text, "PRODUCT_MANUFACTURER", "96Boards")

    # AOSP ATV evaluates PRODUCT_SUPPORTS_CAMERA with ?= while atv_base.mk is inherited
    # from Rockchip common device.mk. The value therefore MUST exist before that inherit
    # is parsed; appending it at the end of the product is too late to remove cameraserver.
    inherit_marker = f"$(call inherit-product, device/rockchip/rk3399/{args.product}/device.mk)"
    text = set_make_var_before(
        text,
        "PRODUCT_SUPPORTS_CAMERA",
        "true" if args.camera == "1" else "false",
        inherit_marker,
    )
    product.write_text(text)

    # The Rockchip bcmdhd glue in this pinned kernel requests generic vendor filenames:
    #   /vendor/etc/firmware/fw_bcmdhd.bin
    #   /vendor/etc/firmware/nvram.txt
    # ROCK960 A/B is documented with AP6356S, and this exact vendor release contains the
    # matching AP6356S NVRAM plus BCM4356A2 firmware. Install explicit aliases instead of
    # inheriting the historical AP6354 board label. APSTA/P2P aliases are installed too so
    # Android hotspot/P2P paths do not need to reuse an AP6354 calibration file.
    device_mk = dst / "device.mk"
    device_text = device_mk.read_text().rstrip() + "\n\n"
    device_text += "# ROCK960 AP6356S Wi-Fi firmware aliases (generated by controller)\n"
    device_text += "ROCK960_WIFI_FIRMWARE_DIR := vendor/rockchip/common/wifi/firmware\n"
    device_text += "PRODUCT_COPY_FILES += \\\n"
    device_text += "    $(ROCK960_WIFI_FIRMWARE_DIR)/fw_bcm4356a2_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcmdhd.bin \\\n"
    device_text += "    $(ROCK960_WIFI_FIRMWARE_DIR)/fw_bcm4356a2_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcmdhd_apsta.bin \\\n"
    device_text += "    $(ROCK960_WIFI_FIRMWARE_DIR)/fw_bcm4356a2_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/fw_bcmdhd_p2p.bin \\\n"
    device_text += "    $(ROCK960_WIFI_FIRMWARE_DIR)/nvram_ap6356s.txt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/nvram.txt\n"
    device_mk.write_text(device_text)

    # Preserve the upstream RK3399 ATV partition map verbatim. On the 2.0.8 release the
    # fixed partitions end at sector 0x0076d400 (~3.71 GiB), leaving the rest for userdata.
    (dst / "ROCK960_PORT_GENERATED.txt").write_text(
        "Generated from ASUS/TinkerBoard RK3399 ATV Android 11 product.\n"
        "Board DTS: rk3399-rock960-ab-android\n"
        f"AVB: {'enabled' if args.avb == '1' else 'disabled for bring-up'}\n"
        f"Camera framework: {'enabled' if args.camera == '1' else 'disabled'}\n"
        f"Ethernet product feature: {'enabled' if args.ethernet == '1' else 'disabled'}\n"
        "Wi-Fi module: AP6356S\n"
        "Wi-Fi firmware: BCM4356A2 ag/apsta/p2p aliases\n"
        "Wi-Fi NVRAM: nvram_ap6356s.txt -> /vendor/etc/firmware/nvram.txt\n"
    )

    print(dst)


if __name__ == "__main__":
    main()
